blog/urls.py
from django.urls import re_path
from . import views

app_name = 'blog'

urlpatterns = [
	re_path(r'^$', views.blog_list, name='blog_list'),
	re_path(r'^chu-de/(?P<category_slug>[-\w\d]+)/$', views.blog_list, name="blog_list_by_category"),
	re_path(r'^(?P<slug>[-\w\d]+)/$', views.blog_detail, name='blog_detail'),
]

cart/urls.py
from django.urls import re_path
from . import views

app_name = 'cart'

urlpatterns = [
	re_path(r'^$', views.cart_detail, name='cart_detail'),
	re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
	re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    # path('download/', include('download.urls')),
    path('gio-hang/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('blog/', include('blog.urls')),
    path('search/', include('search.urls')),
    path('help/', include('help.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('', include('shop.urls')),
    path('', views.index, name='main_index')
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import re_path
from . import views

app_name = 'orders'

urlpatterns = [
	re_path(r'^create/$', views.order_create, name='order_create'),
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
	path('', views.product_list, name='product_list'),
	# path('', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator

class CartAddProductForm(forms.Form):
	quantity = forms.IntegerField(label='Số lượng', initial=1, min_value=1)
	update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .cart import Cart 
from .forms import CartAddProductForm
from products.models import ForexProduct 

# Create your views here.

@require_POST
def cart_add(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(ForexProduct, id=product_id)
	form = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
	return redirect('cart:cart_detail')

def cart_remove(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(ForexProduct, id=product_id)
	cart.remove(product)
	return redirect('cart:cart_detail')

def cart_detail(request):
	cart = Cart(request)
	for item in cart:
		item['update_quantity_form'] = CartAddProductForm(initial={'quantity':item['quantity'], 'update':True})
	return render(request, 'cart/detail.html', {'cart':cart})

cart/templates/cart/detail.html
{% extends 'base/base.html' %}

{% block content %}

{% load static %}
		<p class="d-none page-title">Giỏ hàng</p>
		<!-- Gio hang -->
		<div id="cart_detail_gio_hang_laptop_ipad container" class="row flex-column align-items-start gio-hang-page-box">
			<div class="gio-hang-box">	
				<h1 class="capital_gio_hang">GIỎ HÀNG</h1>
			</div>
			<div class="gio-hang-table">
				<table id="gio-hang">
					<thead>
						<tr>
							<th class="gio-hang-page-text">Hình ảnh</th>
							<th class="gio-hang-page-text">Sản phẩm</th>
							<th class="gio-hang-page-text">Đơn giá</th>
							<th class="gio-hang-page-text">Xóa</th>
						</tr>	
					</thead>
					<tbody>
					{% for item in cart %}
                   		{% with product=item.product %}
                   			{% if item.quantity > 0 %}
								<tr>
									<td>
										<a href="{{ product.get__absolute_url }}">
		                                    <img class="table_image" src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="{{ product.name }}">
		                                </a>
									</td>
									<td class="san_pham_text">{{ product.name }}</td>
									<td class="gio-hang-page-text"><p class="don_gia grey_color_text">{{ item.price }} VNĐ</p></td>
									
									<td>
		                                <a href="{% url "cart:cart_remove" product.id %}"><img src="{% static 'img/x_symbol.png' %}" alt="x symbol" style="height: 13px; width: auto"></a>
		                            </td>
								</tr>
							{% endif %}
						{% endwith %}
					{% endfor %}
                    <tr>
                    	<td></td>
                    	<td></td>
                    	<td></td>
                    	<td></td>
	                    <td class="sumtotal gio-hang-page-text">Tổng cộng:</td>
	                    <td><p class="sumtotal gio-hang-page-text" id="tong_cong">{{ cart.get_total_price }} VNĐ</p></td>
	                </tr>
	                </tbody>
				</table>
				<div class="gio-hang-flex-box">
				    {% if cart|length > 0 %}
						<div class="gio-hang-flex-item gio-hang-page-text">
					        <a href="{% url "orders:order_create" %}" class="genric-btn primary circle">Đặt hàng</a>				        
					    </div>
					{% endif %}
					<div class="gio-hang-flex-item gio-hang-page-text">				  
				        <a href="{% url "products:product_list" %}" class="genric-btn primary-border circle">Tiếp tục mua hàng</a>
				    </div>					    
				</div>
			</div>
		</div>
		<!-- End Gio hang -->

		<!-- Gio hang -->
		<div id="cart_detail_gio_hang_iphone" class="row flex-column align-items-start gio-hang-page-box">
			<div class="gio-hang-box">	
				<h1 class="capital_gio_hang">Giỏ hàng</h1>
			</div>
			<div class="gio-hang-table">
				<table id="gio-hang" style="padding: 0; width: 100%;">
					<tbody>
					{% for item in cart %}
                   		{% with product=item.product  %}
                   			{% if item.quantity > 0 %}
								<tr>
									<td id="td_image">
										<a href="{{ product.get__absolute_url }}">
		                                    <img class="table_image" src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="{{ product.name }}">
		                                </a>
									</td>
									<td id="td_name" class="san_pham_text">
										<h2 style="font-size: 14px; line-height: 20px;">{{ product.name }}</h2>
										<p style="font-size: 14px; line-height: 20px; padding-top: 5px;" class="don_gia grey_color_text">{{ item.price }} &#x20AB</p>
									</td>
									
									<td id="td_remove">
		                                <a href="{% url "cart:cart_remove" product.id %}"><img src="{% static 'img/x_symbol.png' %}" alt="x symbol" style="height: 13px; width: auto"></a>
		                            </td>
								</tr>
							{% endif %}
						{% endwith %}
					{% endfor %}
	                </tbody>
				</table>
				<div class="row">
					<div class="sumtotal gio-hang-page-text tong_cong_padding">Tổng cộng:</div> 
					<div><p class="sumtotal gio-hang-page-text" id="tong_cong">{{ cart.get_total_price }} &#x20AB</p></div>
				</div>
				<div class="dat_mua_hang">
					{% if cart|length > 0 %}
					<div>
				        <a href="{% url "orders:order_create" %}" class="genric-btn primary circle">Đặt hàng</a>				        
				    </div>
				    {% endif %}
					<div>				  
				        <a href="{% url "products:product_list" %}" class="genric-btn primary-border circle">Tiếp tục mua hàng</a>
				    </div>					    
				</div>
			</div>
		</div>
		<!-- End Gio hang -->

{% endblock %}