blog/urls.py
from django.urls import re_path
from . import views

app_name = 'blog'

urlpatterns = [
	re_path(r'^$', views.blog_list, name='blog_list'),
	re_path(r'^chu-de/(?P<category_slug>[-\w\d]+)/$', views.blog_list, name="blog_list_by_category"),
	re_path(r'^(?P<slug>[-\w\d]+)/$', views.blog_detail, name='blog_detail'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    # path('download/', include('download.urls')),
    path('gio-hang/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('blog/', include('blog.urls')),
    path('search/', include('search.urls')),
    path('help/', include('help.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('', include('shop.urls')),
    path('', views.index, name='main_index')
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

help/urls.py
from django.urls import re_path
from . import views

app_name = 'help'

urlpatterns = [
	re_path(r'^$', views.help_list, name='help_list'),
	re_path(r'^chu-de/(?P<category_slug>[-\w\d]+)/$', views.help_list, name="help_list_by_category"),
	re_path(r'^(?P<slug>[-\w\d]+)/$', views.help_detail, name='help_detail'),
]

blog/models.py
import random
import os

from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify
from ckeditor_uploader.fields import RichTextUploadingField

# Fancy stuffs first=============================================================================

def get_filename_ext(filepath):
	base_name = os.path.basename(filepath)
	name, ext = os.path.splitext(base_name)
	return name, ext 

def upload_image_path(instance, filename):
	new_filename = 'trung-awesome-programmer-{random_integer}'.format(random_integer=random.randint(1, 145146)) 
	name, ext = get_filename_ext(filename)
	final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
	return 'blog_images/{new_filename}/{final_filename}'.format(new_filename=new_filename, final_filename=final_filename)

# Model managers and custom querysets:
class MyBlogPostQuerySet(models.QuerySet):
	def filter_by_search_blogs(self, request):
		if request.GET:
			query = request.GET.get('q')
			parameter = models.Q(name__icontains=query) | models.Q(hashtag__icontains=query) | models.Q(author__icontains=query) | models.Q(content__icontains=query) | models.Q(category__name__icontains=query) | models.Q(category__description__icontains=query)
			blogs = self.filter(parameter).distinct()
		return blogs 

class BlogPostManager(models.Manager):
	def get_queryset(self):
		return MyBlogPostQuerySet(self.model, using=self._db)
	def filter_by_search_blogs(self, request):
		return self.get_queryset().filter_by_search_blogs(request)

# Models
class BlogCategory(models.Model):
	name = models.CharField(max_length=255, db_index=True, verbose_name="Tên")
	slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL", blank=True)
	description = models.TextField(blank=True, verbose_name="Mô tả")
	created_at = models.DateTimeField(auto_now_add=True, verbose_name="Tạo mới")
	updated_at = models.DateTimeField(auto_now=True, verbose_name="Cập nhật")

	def __str__(self):
		return self.name

	class Meta:
		ordering = ['-created_at']
		verbose_name = 'Danh mục blog'
		verbose_name_plural = 'Danh mục blog'

	def save(self):
		if not self.slug:
			self.slug = slugify(self.name.replace('đ', 'd'))
		super(BlogCategory, self).save()

	def get_absolute_url(self):
		return reverse('blog:blog_list_by_category', args=[self.slug])


class BlogPost(models.Model):
	category = models.ForeignKey(BlogCategory, on_delete=models.CASCADE, verbose_name="Danh mục")
	name = models.CharField(max_length=255, db_index=True, verbose_name="Tiêu đề")
	slug = models.SlugField(max_length=255, db_index=True, unique=True, verbose_name="URL", blank=True)
	created_at = models.DateTimeField(auto_now_add=True, verbose_name="Tạo mới")
	updated_at = models.DateTimeField(auto_now=True, verbose_name="Cập nhật")
	author = models.CharField(max_length=100, blank=True, verbose_name="Tác giả")
	hashtag = models.CharField(max_length=500, blank=True)
	main_img = models.ImageField(upload_to=upload_image_path, blank=True, verbose_name="Ảnh blog")

	content = RichTextUploadingField(blank=True, verbose_name="Nội dung")

	# paragraph_1 = models.TextField(blank=True, verbose_name="Đoạn 1")
	# img_1 = models.ImageField(upload_to=upload_image_path, blank=True, verbose_name="Ảnh 1")
	# img_description_1 = models.CharField(max_length=300, blank=True, verbose_name="Caption ảnh 1")
	# paragraph_2 = models.TextField(blank=True, verbose_name="Đoạn 2")
	# img_2 = models.ImageField(upload_to=upload_image_path, blank=True, verbose_name="Ảnh 2")
	# img_description_2 = models.CharField(max_length=300, blank=True, verbose_name="Caption ảnh 2")
	# paragraph_3 = models.TextField(blank=True, verbose_name="Đoạn 3")
	# img_3 = models.ImageField(upload_to=upload_image_path, blank=True, verbose_name="Ảnh 3")
	# img_description_3 = models.CharField(max_length=300, blank=True, verbose_name="Caption ảnh 3")
	# paragraph_4 = models.TextField(blank=True, verbose_name="Đoạn 4")
	# img_4 = models.ImageField(upload_to=upload_image_path, blank=True, verbose_name="Ảnh 4")
	# img_description_4 = models.CharField(max_length=300, blank=True, verbose_name="Caption ảnh 4")
	# paragraph_5 = models.TextField(blank=True, verbose_name="Đoạn 5")
	# img_5 = models.ImageField(upload_to=upload_image_path, blank=True, verbose_name="Ảnh 5")
	# img_description_5 = models.CharField(max_length=300, blank=True, verbose_name="Caption ảnh 5")
	# paragraph_6 = models.TextField(blank=True, verbose_name="Đoạn 6")
	# img_6 = models.ImageField(upload_to=upload_image_path, blank=True, verbose_name="Ảnh 6")
	# img_description_6 = models.CharField(max_length=300, blank=True, verbose_name="Caption ảnh 6")
	# paragraph_7 = models.TextField(blank=True, verbose_name="Đoạn 7")
	# img_7 = models.ImageField(upload_to=upload_image_path, blank=True, verbose_name="Ảnh 7")
	# img_description_7 = models.CharField(max_length=300, blank=True, verbose_name="Caption ảnh 7")
	# paragraph_8 = models.TextField(blank=True, verbose_name="Đoạn 8")
	# img_8 = models.ImageField(upload_to=upload_image_path, blank=True, verbose_name="Ảnh 8")
	# img_description_8 = models.CharField(max_length=300, blank=True, verbose_name="Caption ảnh 8")

	objects = BlogPostManager()

	def __str__(self):
		return self.name

	class Meta:
		ordering = ['-created_at']
		verbose_name = "Bài blog"
		verbose_name_plural = "Bài blog"

	def split_to_single_tags(self):
		single_tags = self.hashtag.split(', ')
		return single_tags

	def save(self):
		if not self.slug:
			self.slug = slugify(self.name.replace('đ', 'd'))
		super(BlogPost, self).save()

	def get_absolute_url(self):
		return reverse('blog:blog_detail', args=[self.slug])

class BlogComment(models.Model):
	blog_post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, verbose_name="Bài blog")
	author = models.CharField(max_length=100, verbose_name="Tác giả")
	email = models.EmailField(blank=True)
	created_at = models.DateTimeField(auto_now_add=True, verbose_name="Tạo mới")
	updated_at = models.DateTimeField(auto_now=True, verbose_name="Cập nhật")
	content = models.TextField(verbose_name="Nội dung", max_length=2000)
	allow = models.BooleanField(default=True, blank=True, verbose_name="Cho phép")

	def __str__(self):
		return self.author

	class Meta:
		ordering = ['-updated_at']
		verbose_name = "Bình luận"
		verbose_name_plural = "Bình luận"

help/models.py
import random
import os

from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify
from ckeditor_uploader.fields import RichTextUploadingField

# Fancy stuffs first=============================================================================

def get_filename_ext(filepath):
	base_name = os.path.basename(filepath)
	name, ext = os.path.splitext(base_name)
	return name, ext 

def upload_image_path(instance, filename):
	new_filename = 'trung-awesome-programmer-{random_integer}'.format(random_integer=random.randint(1, 145146)) 
	name, ext = get_filename_ext(filename)
	final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
	return 'help_images/{new_filename}/{final_filename}'.format(new_filename=new_filename, final_filename=final_filename)

# Model managers and custom querysets:
class MyHelpPostQuerySet(models.QuerySet):
	def filter_by_search_helps(self, request):
		if request.GET:
			query = request.GET.get('q')
			parameter = models.Q(name__icontains=query) | models.Q(hashtag__icontains=query) | models.Q(author__icontains=query) | models.Q(content__icontains=query) | models.Q(category__name__icontains=query) | models.Q(category__description__icontains=query)
			helps = self.filter(parameter).distinct()
		return helps 

class HelpPostManager(models.Manager):
	def get_queryset(self):
		return MyHelpPostQuerySet(self.model, using=self._db)
	def filter_by_search_helps(self, request):
		return self.get_queryset().filter_by_search_helps(request)

# Models
class HelpCategory(models.Model):
	name = models.CharField(max_length=255, db_index=True, verbose_name="Tên")
	slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL", blank=True)
	description = models.TextField(blank=True, verbose_name="Mô tả")
	created_at = models.DateTimeField(auto_now_add=True, verbose_name="Tạo mới")
	updated_at = models.DateTimeField(auto_now=True, verbose_name="Cập nhật")

	def __str__(self):
		return self.name

	class Meta:
		ordering = ['-created_at']
		verbose_name = 'Danh mục help'
		verbose_name_plural = 'Danh mục help'

	def save(self):
		if not self.slug:
			self.slug = slugify(self.name.replace('đ', 'd'))
		super(HelpCategory, self).save()

	def get_absolute_url(self):
		return reverse('help:help_list_by_category', args=[self.slug])


class HelpPost(models.Model):
	category = models.ForeignKey(HelpCategory, on_delete=models.CASCADE, verbose_name="Danh mục")
	name = models.CharField(max_length=255, db_index=True, verbose_name="Tiêu đề")
	slug = models.SlugField(max_length=255, db_index=True, unique=True, verbose_name="URL", blank=True)
	created_at = models.DateTimeField(auto_now_add=True, verbose_name="Tạo mới")
	updated_at = models.DateTimeField(auto_now=True, verbose_name="Cập nhật")
	author = models.CharField(max_length=100, blank=True, verbose_name="Tác giả")
	hashtag = models.CharField(max_length=500, blank=True)
	main_img = models.ImageField(upload_to=upload_image_path, blank=True, verbose_name="Ảnh help")

	content = RichTextUploadingField(blank=True, verbose_name="Nội dung")

	objects = HelpPostManager()

	def __str__(self):
		return self.name

	class Meta:
		ordering = ['-created_at']
		verbose_name = "Bài help"
		verbose_name_plural = "Bài help"

	def split_to_single_tags(self):
		single_tags = self.hashtag.split(', ')
		return single_tags

	def save(self):
		if not self.slug:
			self.slug = slugify(self.name.replace('đ', 'd'))
		super(HelpPost, self).save()

	def get_absolute_url(self):
		return reverse('help:help_detail', args=[self.slug])

class HelpComment(models.Model):
	help_post = models.ForeignKey(HelpPost, on_delete=models.CASCADE, verbose_name="Bài help")
	author = models.CharField(max_length=100, verbose_name="Tác giả")
	email = models.EmailField(blank=True)
	created_at = models.DateTimeField(auto_now_add=True, verbose_name="Tạo mới")
	updated_at = models.DateTimeField(auto_now=True, verbose_name="Cập nhật")
	content = models.TextField(verbose_name="Nội dung", max_length=2000)
	allow = models.BooleanField(default=True, blank=True, verbose_name="Cho phép")

	def __str__(self):
		return self.author

	class Meta:
		ordering = ['-updated_at']
		verbose_name = "Bình luận"
		verbose_name_plural = "Bình luận"

help/forms.py
from django.forms import ModelForm, TextInput, EmailInput, Textarea

from .models import HelpComment

class HelpCommentForm(ModelForm):
	class Meta:
		model = HelpComment
		fields = ['author', 'email', 'content']
		widgets = {
			'author': TextInput(attrs={
					'placeholder': 'Tên *',
					'class': 'my-1 maven_font form-control',
					'style': 'font-size: 15px;',
				}),
			'email': EmailInput(attrs={
					'placeholder': 'Email',
					'class': 'my-1 maven_font form-control',
					'style': 'font-size: 15px;',
				}),
			'content': Textarea(attrs={
					'placeholder': 'Nội dung *',
					'class': 'my-1 maven_font form-control',
					'style': 'height: 110px; font-size: 15px;',
				}),
		}

help/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from .models import HelpPost, HelpCategory, HelpComment
from .forms import HelpCommentForm

# Create your views here.

def help_list(request, category_slug=None):
	category = None
	categories = HelpCategory.objects.all()
	helps = HelpPost.objects.all()

	if category_slug:
		category = get_object_or_404(HelpCategory, slug=category_slug)
		helps = HelpPost.objects.filter(category=category)

	paginator = Paginator(helps, 15)
	current_page = request.GET.get('page')
	helps = paginator.get_page(current_page)
	try:
		int_current_page = int(current_page)
	except TypeError:
		int_current_page = 1

	context = {
		'helps': helps,
		'category': category,
		'categories': categories,
		'paginator': paginator,
		'int_current_page': int_current_page,
	}

	return render(request, 'help/help_list.html', context)

def help_detail(request, slug):
	help_post = get_object_or_404(HelpPost, slug=slug)
	related_post = HelpPost.objects.filter(category=help_post.category).exclude(slug=slug)[:5]
	comments = HelpComment.objects.filter(help_post=help_post, allow=True)

	try:
		prev_post = HelpPost.objects.filter(pk__lt=help_post.pk)[0]
	except IndexError:
		prev_post = None

	try:
		next_post = HelpPost.objects.filter(pk__gt=help_post.pk).order_by('pk')[0]
	except IndexError:
		next_post = None

	form = HelpCommentForm()
	if request.POST:
		form = HelpCommentForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			HelpComment.objects.create(
					author = cd['author'],
					email = cd['email'],
					content = cd['content'],
					help_post = help_post,
					allow = True,
				)
			return redirect('help:help_detail', slug=slug)

	context = {
		'help_post': help_post,
		'related_post': related_post,
		'prev_post': prev_post,
		'next_post': next_post,
		'form': form,
		'comments': comments,
	}

	return render(request, 'help/help_detail.html', context)

help/templates/help/help_list.html
{% extends 'base/base.html' %}

{% block content %}

{% load static %}
		<p class="d-none page-title">Blog</p>
		<div class="container">
			<div class="row">
				<div class="col-12 col-md-3">
					<div class="text-center d-block d-md-none">
						<h1 id="blog-list-heading" class="merry_whether_font pt-4" style="font-size: 24px; color: #888">Unee's Blog</h1>
						<h2 id="blog-category-heading" class="merry_whether_font pb-3" style="font-size: 15px; color: #888">Chủ đề: <p class="d-inline" style="color: #6cbb23">{% if category %} {{ category.name }} {% else %} Tất cả {% endif %}</p></h2>
					</div>							
				</div>
				<div class="d-none d-md-block col-8">
					<div class="pl-4 d-none d-md-block text-center">
						<h1 id="blog-list-heading" class="merry_whether_font pt-4" style="font-size: 24px; color: #888">Unee's Blog</h1>
						<h2 id="blog-category-heading" class="merry_whether_font pb-3" style="font-size: 15px; color: #888">Chủ đề: <p class="d-inline" style="color: #6cbb23">{% if category %} {{ category.name }} {% else %} Tất cả {% endif %}</p></h2>
					</div>
				</div>
			</div>
			<div class="row maven_font">
				<div class="px-3 d-none d-md-block col-3" id="blog-detail-nav">
				{% if categories %}
					<div>
						<h2 class="maven_font pb-1 px-2 mb-2 rounded">Chủ đề</h2>
						<ul>
							<li class="py-2 ml-3"><a class="related-post-list" href="{% url 'blog:blog_list' %}">Tất cả</a></li>
							{% for cate in categories %}
							<li class="py-2 ml-3"><a class="related-post-list" href="{{ cate.get_absolute_url }}">{{ cate.name }}</a></li>
							{% endfor %}
						</ul>
					</div>
				{% endif %}
				</div>
				<div class="px-4 px-md-5 col-12 col-md-8" id="blog-post">
					{% for blog in helps %}
						{% autoescape off %}
						<!-- Blog title -->
						<section>
							<div class="pb-1" id="blog-title">
								<h1 class="merry_whether_font text-center"><a class="dark_color_text" href="{{ blog.get_absolute_url }}">{{ blog.name }}</a></h1>
							</div>
						</section>

						<!-- Blog date, author -->
						<section>
							<div class="" id="blog-date-author">
								<h3 class="merry_whether_font dark_color_text text-center">Đăng ngày {{ blog.created_at|date:"j/n/Y" }} bởi <a href="/search/?q={{ blog.author }}">{{ blog.author }}</a></h3>
							</div>
							<div class="d-block mx-auto mt-10" id="separate-title-and-content" style="height: 20px;"></div>			
						</section>

						<!-- Blog image -->
						{% if blog.main_img %}
						<section>
							<div class="mb-10 text-center" id="blog-image">
								<a href="{{ blog.get_absolute_url }}"><img src="{{ blog.main_img.url }}"  alt="Ảnh bìa blog"></a>
							</div>
						</section>
						{% endif %}

						<!-- Blog content summary -->
						{% if blog.content %}
							<div class="blog-content-paragraph"> 
								<div class="blog-content-text">{{ blog.content|truncatewords:50 }}</div>
							</div>
						{% endif %}

						<!-- Xem them -->
						<div class="text-center my-2">
							<a id="continue-reading" href="{{ blog.get_absolute_url }}" class="genric-btn primary-border radius maven_font"><p class="p-0 m-0">Đọc tiếp...</p></a>
						</div>

						<!-- Chu de, comment -->
						<div class="row py-1 mt-3 mb-4 mb-md-5 mx-1" id="category-comment-row">
							<div class="col-8 p-0 m-0">
								<p class="p-0 m-0">Chủ đề: <a href="{% url 'blog:blog_list_by_category' blog.category.slug %}">{{ blog.category }}</a></p>
								{% if blog.hashtag %}
								<p class="p-0 m-0">Hashtags: {% for tag in blog.split_to_single_tags %}<a href="/search/hashtags/?q={{ tag }}">{{ tag }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</p>
								{% endif %}
							</div>
							{% if blog.blogcomment_set.all|length > 0 %}
							<div class="col-4 p-0 m-0 d-flex flex-row-reverse align-items-center">
								<p class="p-0 m-0"><a href="{{ blog.get_absolute_url }}#tra-loi">{{ blog.blogcomment_set.all|length }} Bình luận</a></p>
							</div>
							{% else %}
							<div class="col-4 p-0 m-0 d-flex flex-row-reverse align-items-center">
								<p class="p-0 m-0"><a href="{{ blog.get_absolute_url }}#binh-luan">Viết bình luận</a></p>
							</div>
							{% endif %}
						</div>	
						{% endautoescape %}
					{% endfor %}
				</div>
			</div>
			<div class="d-none d-md-block">
				{% if helps.paginator.num_pages > 1 %}
				<div class="relative py-4">
					<div class="d-flex flex-row-reverse">
						<div class="px-3"><a href="?page={{ helps.paginator.num_pages }}"><i class="paginator fa fa-angle-double-right""></i></a></div>
						<div class="px-3"><a {% if helps.has_next %} href="?page={{ helps.next_page_number }}" {% else %} href="?page={{ helps.paginator.num_pages }}" {% endif %}><i class="paginator fa fa-angle-right"></i></a></div>
						<div class="px-2">
							<div>
							{% for destination_page in paginator.page_range %}
								<div class="px-2 d-inline"><a {% if int_current_page == destination_page %} class="paginator-active" {% else %} class="dark_color_text paginator"  {% endif %} href="?page={{ destination_page }}">{{ destination_page }}</a></div>
							{% endfor %}
							</div>
						</div>
						<div class="px-3"><a {% if helps.has_previous %} href="?page={{ helps.previous_page_number }}" {% else %} href="?page=1" {% endif %}><i class="paginator fa fa-angle-left"></i></a></div>
						<div class="px-3"><a href="?page=1"><i class="paginator fa fa-angle-double-left"></i></a></div>
					</div>
				</div>
				{% endif %}
			</div>
			<div class="d-block d-md-none">
				{% if helps.paginator.num_pages > 1 %}
				<div class="relative py-3 text-center">
					<div class="px-1 d-inline"><a href="?page=1"><i class="paginator-iphone fa fa-angle-double-left"></i></a></div>
					<div class="px-1 d-inline"><a {% if helps.has_previous %} href="?page={{ helps.previous_page_number }}" {% else %} href="?page=1" {% endif %}><i class="paginator-iphone fa fa-angle-left"></i></a></div>
					<div class="px-1 d-inline">
					{% for destination_page in paginator.page_range %}
						<div class="px-2 d-inline"><a {% if int_current_page == destination_page %} class="paginator-iphone-active" {% else %} class="dark_color_text paginator-iphone"  {% endif %} href="?page={{ destination_page }}">{{ destination_page }}</a></div>
					{% endfor %}
					</div>
					<div class="px-1 d-inline"><a {% if helps.has_next %} href="?page={{ helps.next_page_number }}" {% else %} href="?page={{ helps.paginator.num_pages }}" {% endif %}><i class="paginator-iphone fa fa-angle-right"></i></a></div>
					<div class="px-1 d-inline"><a href="?page={{ helps.paginator.num_pages }}"><i class="paginator-iphone fa fa-angle-double-right""></i></a></div>
				</div>
				{% endif %}
			</div>
		</div>

{% endblock %}

		        