blog/urls.py
from django.urls import re_path
from . import views

app_name = 'blog'

urlpatterns = [
	re_path(r'^$', views.blog_list, name='blog_list'),
	re_path(r'^chu-de/(?P<category_slug>[-\w\d]+)/$', views.blog_list, name="blog_list_by_category"),
	re_path(r'^(?P<slug>[-\w\d]+)/$', views.blog_detail, name='blog_detail'),
]

cart/urls.py
from django.urls import re_path
from . import views

app_name = 'cart'

urlpatterns = [
	re_path(r'^$', views.cart_detail, name='cart_detail'),
	re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
	re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    # path('download/', include('download.urls')),
    path('gio-hang/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('blog/', include('blog.urls')),
    path('search/', include('search.urls')),
    path('help/', include('help.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('', include('shop.urls')),
    path('', views.index, name='main_index')
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
	path('', views.product_list, name='product_list'),
	# path('', views.product_detail, name='product_detail'),
]

products/models.py
from django.db import models
from django.template.defaultfilters import slugify

from ckeditor_uploader.fields import RichTextUploadingField


class ForexProduct(models.Model):
	name = models.CharField('Thời hạn', max_length=255)
	stt = models.IntegerField(blank=True, null=True)
	image = models.ImageField(upload_to='forex_products', blank=True, null=True)
	note = RichTextUploadingField('Ghi chú', blank=True, null=True)
	price = models.IntegerField('Giá')
	available = models.BooleanField(default=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ['stt', '-updated_at']
		verbose_name = 'Sản phẩm'
		verbose_name_plural = 'Sản phẩm'

	def __str__(self):
		return self.name

	# def get_absolute_url(self):
	# 	return reverse('products:product_detail', args=(self.pk,))

products/views.py
from django.shortcuts import render, get_object_or_404

from .models import ForexProduct


def product_list(request):
	products = ForexProduct.objects.filter(available=True)
	paid_products = ForexProduct.objects.filter(available=True, price__gt=0)

	context = {
		'products': products,
		'paid_products': paid_products,
	}

	return render(request, 'products/product_list.html', context)

# def product_detail(request, pk):
# 	product = get_object_or_404(ForexProduct, pk=pk)

# 	context = {
# 		'product': product
# 	}

# 	return render(request, 'products/product_detail.html', context)

products/templates/products/product_list.html
{% extends 'base/base.html' %}
{% block content %}
{% load static %}
		
	<section class="container mb-5">
		<h1 class="text-center mt-5 mb-3">Tick data 99%</h1>

		<h2 class="text-center mb-3">Instruction</h2>
		<p class="text-center mb-3" style="width: 70%; margin: 0 auto;">
			It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors.
		</p>

		<b>
			<p class="text-center" style="width: 70%; margin: 0 auto;">
				If your email has already been activated: 
				<span class="pl-2">
					<a href="#">Click here</a>
				</span>
			</p>
		</b>
			
	</section>

	<section class="container mb-5">
		<table class="table table-striped mb-5">
			<thead>
				<tr>
					<th scope="col"></th>
					{% for product in products %}
					<th scope="col" class="text-center">
						{% if product.image %}
						<img src="{{ product.image.url }}" style="width: 90%; object-fit: cover;">
						{% endif %}
						<p>{{ product.name }}</p>
					</th>
					{% endfor %}
				</tr>
			</thead>
			<tbody>
				<tr>
					<th scope="row">Something</th>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>
						<i class="fa fa-check"></i>
					</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>
						<i class="fa fa-times"></i>
					</td>
				</tr>
				<tr>
					<th scope="row">Something</th>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
				</tr>
				<tr>
					<th scope="row">Something</th>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
				</tr>
				<tr>
					<th scope="row">Something</th>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
				</tr>
				<tr>
					<th scope="row">Something</th>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
				</tr>
				<tr>
					<th scope="row">Something</th>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
				</tr>
				<tr>
					<th scope="row">Something</th>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
				</tr>
				<tr>
					<th scope="row">Something</th>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
				</tr>
				<tr>
					<th scope="row">Something</th>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
				</tr>
				<tr>
					<th scope="row">Something</th>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
					<td>Có nhiều phiên bản khác nhau đã xuất hiện</td>
				</tr>
				<tr>
					<th scope="row"></th>
					<td>
						<button class="btn btn-outline-info" style="cursor: pointer;">Free</button>
					</td>
					{% for product in paid_products %}
					<td>
						<form class="detail-page-text" action="{% url 'cart:cart_add' product.pk %}" method="post">
			                {% csrf_token %}                                                
			                <input type="hidden" name="quantity" value="1">
			                <button type="submit" class="btn btn-info" style="cursor: pointer;">Buy</button>
			            </form>
					</td>
					{% endfor %}
				</tr>
			</tbody>
		</table>

		<b>
			<p class="text-center" style="width: 70%; margin: 0 auto;">
				If your email has already been activated: 
				<span class="pl-2">
					<a style="color: green;" href="#">Click here</a>
				</span>
			</p>
		</b>
		<p class="text-center" style="width: 70%; margin: 0 auto;">
			If you want data of more than 5 years, contact us:
			<span class="pl-2">
				forextory.support@gmail.com
			</span>
		</p>
	</section>

		

{% endblock %}

		<!-- <section id="list_feature_laptop_ipad" class="feature-area relative">
			<div class="overlay overlay-bg"></div>
			<div class="d-none d-xl-block">
				<div class="san_pham">
					<h2>Tick Data 99%</h2>
				</div>
				
			</div>
			<div class="d-none d-md-block d-xl-none">
				<div class="san_pham">
					<h2 style="font-size: 22px;">Tick Data 99%</h2>
				</div>
				
			</div>
			<div class="" style="margin: auto 12%;">
				<div class="row">
					{% for product in products %}
						<div class="col-6 col-xl-3 align-items-stretch p-0">
							<div class="box_shadow_baby d-flex flex-column m-2 p-2">
								<div class="relative mb-4" onmouseover="showForm({{ forloop.counter0 }})" onmouseleave="hideForm({{ forloop.counter0 }})">
									<div>
										<a href="#">
											<img class="d-block relative w-100" src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" style="z-index: 600; border: 1px solid #fff; border-radius: 4px;" alt="{{ product.name }}">
										</a>
									</div>

									<a href="#">
										<div class="product_desc_box" style="position: absolute; top: 1px; left: 1px; right: 1px; z-index: 20000; opacity: 0; transition: opacity 0.3s; -webkit-transition: opacity 0.3s; cursor: pointer">
											<p>{{ product.description|truncatewords:23 }}</p> 
										</div>
									</a>
									<div class="form_add_cart" style="position: absolute; bottom: 1px; left: 1px; right: 1px; z-index: 20000; opacity: 0; transition: opacity 0.3s; -webkit-transition: opacity 0.3s;">
										<form class="detail-page-text" action="{% url "cart:cart_add" product.id %}" method="post">
							                {% csrf_token %}                                                
							                <input type="hidden" name="quantity" value="1">
							                <input style="width: 100%; font-size: 13px; font-family: 'Maven Pro', sans-serif;" type="submit" value="Thêm vào giỏ" class="genric-btn primary radius">
							            </form>
									</div>
								</div>
								<div class="row" style="min-height: 60px;">
									<div class="col-6 text-center maven_font pr-0">
										<a class="desc_a" style="color: #111; font-size: 18px;" onmouseover="changeTextColorOn({{ forloop.counter0 }})" onmouseleave="changeTextColorOff({{ forloop.counter0 }})" href="#">{{ product.name }}</a>
									</div>
									<div class="col-6 text-center maven_font px-0">
										<p style="color: red; font-size: 18px;">{{ product.price }} &#x20AB</p>
									</div>
								</div>
							</div>
						</div>
					{% endfor %}				
				</div>
				
			</div>
		</section>
		<section id="list_feature_iphone" class="feature-area relative">
			<div class="overlay overlay-bg"></div>
			<div class="px-4">
				<div class="san_pham">
					<h2 style="font-size: 20px;">Tick Data 99%</h2>
				</div>
				
			</div>
			<div class="container_new">
				<div class="row align-items-stretch">
					{% for product in products %}
					<div class="col-6 col-sm-3 align-items-stretch p-0">
						<div class="box_shadow_baby d-flex flex-column m-1 p-1">
							<div class="mb-2">
								<a href="#">
									<img class="d-block relative w-100" src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" style="z-index: 600; border: 1px solid #fff; border-radius: 4px;" alt="{{ product.name }}">
								</a>
							</div>
							<div class="w-100 mx-auto row" style="min-height: 40px;">
								<div class="col-6 text-center maven_font py-0">
									<a href="#"><p class="p-0 m-0" style="color: #111; font-size: 12px; line-height: 16px;">{{ product.name }}</p></a>
								</div>
								<div class="col-6 text-center maven_font p-0">
									<p class="p-0 m-0" style="color: red; font-size: 12px; line-height: 16px;">{{ product.price }} &#x20AB</p>
								</div>
							</div>
						</div>
					</div>
					{% endfor %}					
				</div>
			</div>
			
		</section> -->